site_name: TIPS documentation
nav:
  - Introduction: index.md
  - CLI: cli.md
  - Workflow:
    - Overview: workflow/overview.md
    - Strategies:
        - explore: workflow/explore.md
    - Abstract workflows: workflow/abstract.md
    - Implementions: workflow/implementation.md
plugins:
  - mermaid2
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences:
     custom_fences:
       - name: mermaid
         class: mermaid
         format: !!python/name:mermaid2.fence_mermaid
