site_name: TIPS documentation
nav:
  - Introduction: index.md
  - Workflow:
    - Overview: workflow/overview.md
    - Abstract: workflow/abstract.md
    - Strategies:
        - tips/explore: workflow/explore.md
    - Implementions: workflow/implementation.md
  - CLI:
    - Overview: cli/overview.md
    - Commands:
      - convert: cli/convert.md
      - filter: cli/filter.md
plugins:
  - mermaid2
theme:
  name: material
  features:
    - navigation.sections
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences:
     custom_fences:
       - name: mermaid
         class: mermaid
         format: !!python/name:mermaid2.fence_mermaid
extra_css:
  - stylesheets/extra.css
